name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-20.04
    outputs:
      created: ${{ steps.release.outputs.release_created }}
      upload_url: ${{ steps.release.outputs.upload_url }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.TOKEN_PR }}
          release-type: simple
          package-name: conva
          extra-files: |
            ConvA/ConvA.csproj
    
  build-release:
    runs-on: macos-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore ConvA/ConvA.csproj
      - name: Build osx-arm64
        run: dotnet publish ConvA/ConvA.csproj -c Release -r osx-arm64 -o bin/darwin-arm64
      - name: Pack osx-arm64
        run: tar -czvf conva-darwin-arm64.tar.gz -C bin/darwin-arm64 .
      - name: Build osx-amd64
        run: dotnet publish ConvA/ConvA.csproj -c Release -r osx-amd64 -o bin/darwin-amd64
      - name: Pack osx-amd64
        run: tar -czvf conva-darwin-amd64.tar.gz -C bin/darwin-amd64 .
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PR }}
        with:
          upload_url: ${{ needs.release-please.outputs.upload_url }}
          asset_path: ./conva-darwin-amd64.tar.gz
          asset_name: conva-darwin-amd64.tar.gz
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PR }}
        with:
          upload_url: ${{ needs.release-please.outputs.upload_url }}
          asset_path: ./conva-darwin-arm64.tar.gz
          asset_name: conva-darwin-arm64.tar.gz
          asset_content_type: application/octet-stream
      - name: Bump MyHomebrewTap
        run: |
          echo "Bumping MyHomebrewTap ${{ needs.release-please.outputs.tag_name}}"